export const CERTIFICATES = [
  {
    title: "Advanced AI and Machine Learning Techniques and Capstone",
    institution: "Microsoft",
    date: "2026-05-09",
    url: "https://coursera-certificate-images.s3.amazonaws.com/582WD6G6O83C",
    credentialId: "582WD6G6O83C",
  },
  {
    title: "Research Methodologies",
    institution: "Queen Mary University of London",
    date: "2025-11-23",
    url: "https://coursera-certificate-images.s3.amazonaws.com/96G5NI0TK59I",
    credentialId: "96G5NI0TK59I",
  },
  {
    title: "Mastering NestJS (by Packt) on Coursera",
    institution: "Packt",
    date: "2026-04-26",
    url: "https://coursera-certificate-images.s3.amazonaws.com/ALETEC8NB3LL",
    credentialId: "ALETEC8NB3LL",
  },
  {
    title: "Introduction to Data Structures and Algorithms",
    institution: "codedamn",
    date: "2023-06-01",
    url: "https://codedamn.com/certificate/verify/3cd56fcf5dbc422d499e57574c92ab32fd7fc406",
    credentialId: "3cd56fcf5dbc422d499e57574c92ab32fd7fc406",
  },
  {
    title: "Business Statistics",
    institution: "NPTEL",
    date: "2022-01-01",
    credentialId: "NPTEL22MG25S2410027202172086",
  },
  {
    title: "Using Python to Access Web Data",
    institution: "University of Michigan",
    date: "2021-11-01",
    url: "https://coursera-certificate-images.s3.amazonaws.com/J5ZFPXOADYAN",
    credentialId: "J5ZFPXOADYAN",
  },
  {
    title: "Data Structures and Performance",
    institution: "University of California San Diego",
    date: "2024-12-25",
    url: "https://coursera-certificate-images.s3.amazonaws.com/O8M9R7DFUI48",
    credentialId: "O8M9R7DFUI48",
  },
  {
    title: "Python Data Structures",
    institution: "University of Michigan",
    date: "2021-01-01",
    url: "https://coursera-certificate-images.s3.amazonaws.com/S9ZFCQMD4J5W",
    credentialId: "S9ZFCQMD4J5W",
  },
  {
    title: "Building Interactive User Interfaces Using React Library",
    institution: "NIIT",
    date: "2024-09-20",
    url: "https://coursera-certificate-images.s3.amazonaws.com/F9SH30C4WTEB",
    credentialId: "F9SH30C4WTEB",
  },
  {
    title: "HTML, CSS, and JavaScript for Web Developers",
    institution: "The Johns Hopkins University",
    date: "2021-12-01",
    url: "https://coursera-certificate-images.s3.amazonaws.com/2KNGNGG9KKBK",
    credentialId: "2KNGNGG9KKBK",
  },
  {
    title: "Java (Basic)",
    institution: "HackerRank",
    date: "2021-09-01",
    url: "https://www.hackerrank.com/certificates/67dabefa14af",
    credentialId: "67dabefa14af",
  },
  {
    title: "Python Basics",
    institution: "University of Michigan",
    date: "2021-02-01",
    url: "https://coursera-certificate-images.s3.amazonaws.com/JNMRFDC8IVXF",
    credentialId: "JNMRFDC8IVXF",
  },
  {
    title: "Programming for Everybody (Getting Started with Python)",
    institution: "University of Michigan",
    date: "2020-12-01",
    url: "https://coursera-certificate-images.s3.amazonaws.com/MQNNJZXNJ5RF",
    credentialId: "MQNNJZXNJ5RF",
  },
];
