export const HOMEPAGE_DATA = {
  heroPills: [
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "NestJS",
    "PostgreSQL",
    "Redis",
    "Docker",
    "AWS",
  ],
  heroStackIcons: [
    "https://cdn.simpleicons.org/react/22d3ee",
    "https://cdn.simpleicons.org/nextdotjs/ffffff",
    "https://cdn.simpleicons.org/nodedotjs/22c55e",
    "https://cdn.simpleicons.org/nestjs/e0234e",
    "https://cdn.simpleicons.org/express/ffffff",
    "https://cdn.simpleicons.org/postgresql/4169e1",
    "https://cdn.simpleicons.org/mysql/4479a1",
    "https://cdn.simpleicons.org/mongodb/47a248",
    "https://cdn.simpleicons.org/redis/dc382d",
    "https://cdn.simpleicons.org/docker/2496ed",
    "https://cdn.simpleicons.org/amazonwebservices/ffffff",
    "https://cdn.simpleicons.org/nginx/009639",
    "https://cdn.simpleicons.org/caddy/00add8",
    "https://cdn.simpleicons.org/traefik/24a1c1",
    "https://cdn.simpleicons.org/graphql/e10098",
    "https://cdn.simpleicons.org/webrtc/ffffff",
    "https://cdn.simpleicons.org/reactquery/ff4154",
    "https://cdn.simpleicons.org/trpc/2596be",
    "https://cdn.simpleicons.org/openai/ffffff",
    "https://cdn.simpleicons.org/tailwindcss/06b6d4",
    "https://cdn.simpleicons.org/github/22c55e",
    "https://cdn.simpleicons.org/gitlab/6366f1",
    "https://cdn.simpleicons.org/figma/rose",
    "https://cdn.simpleicons.org/javascript/green",
  ],
  bioSuffix:
    " I turn product ideas into fast, typed, and deployable web systems with a backend-first sense for reliability.",
  sections: {
    focus: {
      kicker: "focus // what-i-build",
      title: "Where I do my best work",
      description: "Three lanes I keep sharp across every build.",
    },
    stack: {
      kicker: "stack // capabilities",
      title: "The toolkit I reach for",
      description: "A backend-first stack, end to end.",
    },
    projects: {
      kicker: "work // featured",
      title: "Selected case studies",
      linkText: "view all projects",
    },
  },
  buttons: {
    projects: "launch projects",
    contact: "open contact.env",
  },
};
