export const SKILLS = [
  {
    category: "Programming Languages",
    skills: ["Python", "JavaScript", "TypeScript", "Java", "C++"],
  },
  {
    category: "Frameworks & Libraries",
    skills: [
      "React",
      "Next.js",
      "Node.js",
      "Express",
      "Django",
      "NestJs",
      "Angular",
      "Spring Boot",
      "FastAPI",
      "Hono",
      "Bun",
      "Deno",
    ],
  },
  {
    category: "Databases",
    skills: [
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Redis",
      "MariaDB",
      "Valkey",
      "SQLite",
      "Pinecone",
      "Qdrant",
    ],
  },
  {
    category: "Messaging Queues/PubSub",
    skills: [
      "RabbitMQ",
      "Kafka",
      "BullMQ",
      "Redis",
      "AWS SNS",
      "AWS SQS",
      "AWS EventBridge",
    ],
  },
  {
    category: "Telemetery & Monitoring",
    skills: [
      "Prometheus",
      "Grafana",
      "ELK Stack",
      "Datadog",
      "Sentry",
      "Signoz",
      "OTEL",
    ],
  },
  {
    category: "Tools & Technologies",
    skills: [
      "Git",
      "Docker",
      "AWS",
      "Figma",
      "REST APIs",
      "TRpc",
      "GraphQL",
      "LLM",
      "Gemini",
      "OpenAI API",
      "Groq API",
      "Ollama",
    ],
  },
  {
    category: "DevOps",
    skills: [
      "Docker",
      "Kubernetes",
      "AWS",
      "NGINX",
      "Linux",
      "Apache",
      "caddy",
      "PM2",
      "Coolify",
      "Netlify",
      "Vercel",
      "Traefik",
      "Haproxy",
    ],
  },
  {
    category: "ORMs",
    skills: ["Sequelize", "Mongoose", "Prisma", "Drizzle ORM", "TypeORM"],
  },
  {
    category: "Protocols",
    skills: [
      "HTTP",
      "HTTPS",
      "TCP",
      "UDP",
      "WebSockets",
      "MQTT",
      "gRPC",
      "Protocol Buffers",
      "OpenAPI",
      "GraphQL",
      "WebRTC",
      "OCPP",
      "OCPI",
      "OICP",
    ],
  },
];

export const SoftSkills = [
  "Communication",
  "Teamwork",
  "Problem Solving",
  "Time Management",
  "Adaptability",
  "Leadership",
  "Creativity",
  "Work Ethic",
];
